package nl.lamia.most.exchange.core

import nl.lamia.most.exchange.sbe.ExecutionReportEncoder
import nl.lamia.most.exchange.sbe.MessageHeaderEncoder
import org.agrona.MutableDirectBuffer
import org.agrona.collections.Long2LongHashMap
import org.agrona.concurrent.UnsafeBuffer

/**
 * The last [capacity] execution reports, as encoded, chained per participant (Design.md §5,
 * "Report sequence and resend").
 *
 * **Written on every node, for every report, whether or not it is delivered.** A follower's egress
 * is mocked and a new leader's goes nowhere until its gateway reconnects, so the reports a
 * participant never received after a failover were generated by the node that now leads, while it
 * could not send them. Every node generates the same reports in the same order, so every node holds
 * the same ring. It is not snapshotted: a restored node holds nothing older than its restore, and
 * says so through [oldestRetainedSeq].
 *
 * Preallocated and allocation-free once a participant has been seen. The two maps grow only on a
 * participant's first report. Overwrite is FIFO, so a participant's retained reports are always one
 * unbroken run of its sequence, from [oldestRetainedSeq] to its newest.
 */
class ReportRing(val capacity: Int) {
    init {
        require(capacity > 0) { "report retention must be positive, got $capacity" }
    }

    /** One encoded report per slot: the SBE header and the body, exactly as a gateway receives it. */
    val buffer: MutableDirectBuffer = UnsafeBuffer(ByteArray(capacity * SLOT_LENGTH))

    private val participantOf = LongArray(capacity)
    private val seqOf = LongArray(capacity)
    private val nextOf = IntArray(capacity)
    private val previousOf = IntArray(capacity)

    /** Each participant's newest slot. */
    private val newestSlot = Long2LongHashMap(INITIAL_PARTICIPANTS, LOAD_FACTOR, NONE.toLong())

    /** Each participant's oldest retained sequence; absent means nothing retained. */
    private val oldestSeq = Long2LongHashMap(INITIAL_PARTICIPANTS, LOAD_FACTOR, 0L)

    private var written = 0L

    /**
     * Takes the next slot for [participantId]'s report [reportSeq], evicting the oldest report in
     * the ring if it is full, and returns the slot. The caller encodes into [offset] of [buffer].
     */
    fun append(participantId: Long, reportSeq: Long): Int {
        val slot = (written % capacity).toInt()
        if (written >= capacity) {
            // The report leaving the ring is the oldest its owner had, since overwrite is FIFO, so
            // that owner's retained run now starts one later.
            oldestSeq.put(participantOf[slot], seqOf[slot] + 1)
        }
        written++

        val previous = newestSlot.get(participantId).toInt()
        // Linked only if the previous slot still holds this participant's preceding report. A
        // participant quiet for a whole ring has had its last slot taken by someone else.
        val linked = previous != NONE && participantOf[previous] == participantId &&
            seqOf[previous] == reportSeq - 1
        if (linked) nextOf[previous] = slot else oldestSeq.put(participantId, reportSeq)
        participantOf[slot] = participantId
        seqOf[slot] = reportSeq
        nextOf[slot] = NONE
        previousOf[slot] = if (linked) previous else NONE
        newestSlot.put(participantId, slot.toLong())
        return slot
    }

    fun offset(slot: Int): Int = slot * SLOT_LENGTH

    fun seqAt(slot: Int): Long = seqOf[slot]

    fun nextOf(slot: Int): Int = nextOf[slot]

    /**
     * The lowest sequence of [participantId]'s still held, or [lastSeq] + 1 when none is: a
     * participant with no reports, one whose every report has been evicted, or any participant on
     * a node restored from a snapshot since.
     */
    fun oldestRetainedSeq(participantId: Long, lastSeq: Long): Long {
        val oldest = oldestSeq.get(participantId)
        return if (oldest == 0L || oldest > lastSeq) lastSeq + 1 else oldest
    }

    /**
     * The slot holding [participantId]'s report [seq], which the caller has established is
     * retained (`oldestRetainedSeq <= seq <= lastSeq`). Found by walking back from the newest, so
     * it costs one step per report newer than [seq] -- what a replay is about to send anyway.
     */
    fun slotOf(participantId: Long, seq: Long, lastSeq: Long): Int {
        var slot = newestSlot.get(participantId).toInt()
        var current = lastSeq
        while (current > seq) {
            slot = previousOf[slot]
            current--
        }
        return slot
    }

    companion object {
        /** The header and the 88-byte body of an ExecutionReport, rounded up to a 32-byte multiple. */
        val SLOT_LENGTH: Int = run {
            val report = MessageHeaderEncoder.ENCODED_LENGTH + ExecutionReportEncoder.BLOCK_LENGTH
            (report + 31) and 31.inv()
        }
        val REPORT_LENGTH: Int = MessageHeaderEncoder.ENCODED_LENGTH + ExecutionReportEncoder.BLOCK_LENGTH

        const val DEFAULT_CAPACITY = 1 shl 20
        private const val NONE = -1
        private const val INITIAL_PARTICIPANTS = 1024
        private const val LOAD_FACTOR = 0.65f
    }
}
