package com.engine.reference

import java.io.File
import java.util.Properties

/**
 * One shard's tradable securities. Loaded identically by the engine, the gateway and the market
 * data process, so a shard has exactly one security list rather than three that must be kept in
 * step by hand.
 */
data class ShardSpec(
    val shardId: Int,
    val securities: List<SecuritySpec>,
) {
    init {
        require(shardId >= 0) { "shardId must be non-negative: $shardId" }
        require(securities.isNotEmpty()) { "shard $shardId defines no securities" }
        require(securities.size <= MAX_SECURITIES_PER_SHARD) {
            "a shard hosts at most $MAX_SECURITIES_PER_SHARD securities, got ${securities.size}"
        }
        requireUnique(securities.map { it.securityId }, "securityId")
        requireUnique(securities.map { it.symbol }, "symbol")
        requireUnique(securities.map { it.isin }, "ISIN")
    }

    val securityIds: IntArray get() = IntArray(securities.size) { securities[it].securityId }

    fun securityById(securityId: Int): SecuritySpec? =
        securities.firstOrNull { it.securityId == securityId }

    fun maxLevelCount(): Int = securities.maxOf { it.levelCount }

    /**
     * A digest of everything that must match. Every process in the shard prints it at startup, and
     * so does every cluster node: geometry decides how a price maps to a ladder level, so a
     * mismatch would diverge the books rather than fail loudly.
     */
    fun fingerprint(): String = java.lang.Long.toHexString(fingerprintValue())

    /**
     * The fingerprint as its underlying 64-bit hash, for anywhere it has to go on a wire or into a
     * snapshot rather than in front of a human. [fingerprint] is this value in hex, so the two can
     * never disagree -- a second implementation that drifted by a separator would report agreement
     * between processes that disagree, which is worse than not checking at all.
     */
    fun fingerprintValue(): Long {
        val canonical = securities.sortedBy { it.securityId }.joinToString(",") { it.canonical() }
        var hash = 1125899906842597L
        for (c in "$shardId|$canonical") hash = hash * 31 + c.code
        return hash
    }

    /**
     * The inverse of [from]. Lives beside it so the two cannot drift: a generator that emits a key
     * the parser does not read, or misses one it requires, fails the round-trip test rather than a
     * deployment.
     */
    fun toProperties(): Properties {
        val properties = Properties()
        properties.setProperty("shard.id", shardId.toString())
        properties.setProperty(
            "shard.securities",
            securities.sortedBy { it.securityId }.joinToString(",") { it.securityId.toString() },
        )
        for (security in securities) {
            val prefix = "security.${security.securityId}"
            properties.setProperty("$prefix.symbol", security.symbol)
            properties.setProperty("$prefix.isin", security.isin)
            properties.setProperty("$prefix.name", security.name)
            properties.setProperty("$prefix.currency", security.currency)
            properties.setProperty("$prefix.priceFloor", security.priceFloor.toString())
            properties.setProperty("$prefix.tickSize", security.tickSize.toString())
            properties.setProperty("$prefix.levelCount", security.levelCount.toString())
            properties.setProperty("$prefix.maxOrders", security.maxOrders.toString())
        }
        return properties
    }

    /**
     * The artifact text: ordered, commented, and byte-identical for identical content.
     *
     * `Properties.store` is not used — it stamps the current time into a comment and emits keys in
     * hash order, so two publishes of the same universe would differ and an operator diffing two
     * releases would learn nothing.
     */
    fun render(): String = buildString {
        appendLine("# Generated by the control plane. Do not edit; edit the database and publish.")
        appendLine("# fingerprint=${fingerprint()}")
        appendLine("#")
        appendLine("# Read identically by the engine, the gateway, market data and discovery.")
        appendLine("# Reference prices and collar widths are deliberately absent: they arrive as")
        appendLine("# SecurityDefinition commands through the replicated log (Design.md §7).")
        appendLine()
        appendLine("shard.id=$shardId")
        val ordered = securities.sortedBy { it.securityId }
        appendLine("shard.securities=${ordered.joinToString(",") { it.securityId.toString() }}")
        for (security in ordered) {
            val prefix = "security.${security.securityId}"
            appendLine()
            appendLine("$prefix.symbol=${security.symbol}")
            appendLine("$prefix.isin=${security.isin}")
            appendLine("$prefix.name=${security.name}")
            appendLine("$prefix.currency=${security.currency}")
            appendLine("$prefix.priceFloor=${security.priceFloor}")
            appendLine("$prefix.tickSize=${security.tickSize}")
            appendLine("$prefix.levelCount=${security.levelCount}")
            appendLine("$prefix.maxOrders=${security.maxOrders}")
        }
    }

    companion object {
        const val MAX_SECURITIES_PER_SHARD = 10

        private fun requireUnique(values: List<Any>, what: String) {
            val duplicates = values.groupBy { it }.filterValues { it.size > 1 }.keys
            require(duplicates.isEmpty()) { "duplicate $what in shard: $duplicates" }
        }

        /**
         * Reads a shard security file:
         *
         * ```
         * shard.id=1
         * shard.securities=1,2
         *
         * security.1.symbol=ACME
         * security.1.isin=US0378331005
         * security.1.name=Acme Corporation
         * security.1.currency=USD
         * security.1.priceFloor=0
         * security.1.tickSize=1000000
         * security.1.levelCount=65536
         * security.1.maxOrders=1000000
         * ```
         *
         * Nothing has a default. A wrong tick size misprices every order silently, and a missing
         * ISIN would be published to every downstream adapter, so both must be stated.
         */
        fun from(properties: Properties): ShardSpec {
            val shardId = required(properties, "shard.id").toIntOrNull()
                ?: error("shard.id must be a number")

            val ids = required(properties, "shard.securities")
                .split(',').map { it.trim() }.filter { it.isNotEmpty() }
                .map { it.toIntOrNull() ?: error("shard.securities contains a non-numeric id: $it") }

            val securities = ids.map { id ->
                SecuritySpec(
                    securityId = id,
                    symbol = required(properties, "security.$id.symbol"),
                    isin = required(properties, "security.$id.isin"),
                    name = required(properties, "security.$id.name"),
                    currency = required(properties, "security.$id.currency"),
                    priceFloor = requiredLong(properties, "security.$id.priceFloor"),
                    tickSize = requiredLong(properties, "security.$id.tickSize"),
                    levelCount = requiredInt(properties, "security.$id.levelCount"),
                    maxOrders = requiredInt(properties, "security.$id.maxOrders"),
                )
            }
            return ShardSpec(shardId, securities)
        }

        fun load(path: String): ShardSpec {
            val file = File(path)
            require(file.isFile) { "shard security file not found: $path" }
            val properties = Properties()
            file.inputStream().use(properties::load)
            return from(properties)
        }

        private fun required(properties: Properties, key: String): String =
            properties.getProperty(key)?.trim()
                ?: error("missing required configuration key: $key")

        private fun requiredLong(properties: Properties, key: String): Long =
            required(properties, key).toLongOrNull() ?: error("$key must be a number")

        private fun requiredInt(properties: Properties, key: String): Int =
            required(properties, key).toIntOrNull() ?: error("$key must be a number")
    }
}
