-- Reference data and shard topology.
--
-- The column constraints mirror the SBE wire types exactly (message-schema.xml): Symbol char[16],
-- Isin char[12], CurrencyCode char[3], SecurityName char[48], ChannelUri char[128]. A row that
-- fits here fits on the wire; one that does not would be silently truncated in the directory
-- broadcast, which is the kind of error that surfaces days later as a mis-routed order.
--
-- What SQL cannot express -- the ISIN check digit, at most ten securities per shard, and the
-- rendered artifact's fingerprint -- is enforced by constructing the real `reference` domain types
-- on every write, so there is exactly one implementation of each rule rather than two that drift.

CREATE TABLE shard (
    shard_id                   INTEGER      PRIMARY KEY CHECK (shard_id >= 0),
    -- The GATEWAY's client-facing endpoints, not the cluster's ingress and egress. Held once here
    -- and emitted into both gateway.properties and discovery.properties, which are two hand-kept
    -- copies today with nothing checking they agree.
    order_entry_channel        VARCHAR(128) NOT NULL CHECK (length(trim(order_entry_channel)) > 0),
    order_entry_stream_id      INTEGER      NOT NULL,
    execution_report_channel   VARCHAR(128) NOT NULL CHECK (length(trim(execution_report_channel)) > 0),
    execution_report_stream_id INTEGER      NOT NULL
);

-- security_id is the primary key and shard_id is a plain column, so "exactly one shard per
-- security" -- the invariant Universe enforces at boot -- is structural here rather than checked.
CREATE TABLE security (
    security_id INTEGER     PRIMARY KEY CHECK (security_id >= 0),
    shard_id    INTEGER     NOT NULL REFERENCES shard (shard_id),
    symbol      VARCHAR(16) NOT NULL UNIQUE CHECK (length(trim(symbol)) > 0),
    isin        CHAR(12)    NOT NULL UNIQUE,
    name        VARCHAR(48) NOT NULL,
    currency    CHAR(3)     NOT NULL,
    -- Fixed point with 8 implied decimals throughout; 1000000 is 0.01.
    price_floor BIGINT      NOT NULL,
    tick_size   BIGINT      NOT NULL CHECK (tick_size > 0),
    level_count INTEGER     NOT NULL CHECK (level_count > 0),
    max_orders  INTEGER     NOT NULL CHECK (max_orders > 0)
);

CREATE INDEX security_shard_idx ON security (shard_id);

-- Authored now, not yet on the wire. The engine has an UNAUTHORIZED_PARTICIPANT reject reason that
-- nothing currently raises; binding a participant to an authenticated session is an open item
-- (Design.md §8), and this table is where that binding will be looked up.
CREATE TABLE participant (
    participant_id BIGINT      PRIMARY KEY CHECK (participant_id > 0),
    name           VARCHAR(64) NOT NULL,
    -- 0 means "default to participant_id", matching SmpId on the wire.
    smp_id         BIGINT      NOT NULL DEFAULT 0 CHECK (smp_id >= 0),
    enabled        BOOLEAN     NOT NULL DEFAULT TRUE
);

-- A published, immutable snapshot. Never updated: republishing allocates the next version, so a
-- release directory a process booted from cannot change under it.
CREATE TABLE spec_release (
    version          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    universe_version BIGINT       NOT NULL,
    directory        VARCHAR(512) NOT NULL,
    note             VARCHAR(256)
);

-- The fingerprint every process in the shard prints at startup. Recorded per release so an
-- operator compares one hex string against the logs instead of diffing files.
CREATE TABLE spec_release_shard (
    version     BIGINT      NOT NULL REFERENCES spec_release (version) ON DELETE CASCADE,
    shard_id    INTEGER     NOT NULL,
    fingerprint VARCHAR(32) NOT NULL,
    PRIMARY KEY (version, shard_id)
);
