-- Session scheduling.
--
-- The schedule lives here and fires here, not in the engine. Determinism is not lost by that: the
-- SessionTransition it emits is sequenced through the replicated log like any other command, so
-- every node applies it at the same log position. What determinism would cost is a trading
-- calendar -- holidays, weekends, DST -- inside the deterministic state machine, where a bug kills
-- every node simultaneously. Business rules belong outside it (Design.md §1).

CREATE TABLE session_schedule (
    name       VARCHAR(64) PRIMARY KEY CHECK (length(trim(name)) > 0),
    -- An IANA zone, not an offset. A market opens at 09:00 local whatever the offset is that week;
    -- storing UTC would shift the open by an hour twice a year.
    zone       VARCHAR(64) NOT NULL,
    -- Comma-separated day names, so a venue that trades seven days a week can say so.
    weekdays   VARCHAR(64) NOT NULL,
    -- Off-session housekeeping, constrained to run before the first transition of the day.
    purge_time TIME,
    enabled    BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE TABLE session_schedule_entry (
    schedule_name VARCHAR(64) NOT NULL REFERENCES session_schedule (name) ON DELETE CASCADE,
    at_time       TIME        NOT NULL,
    phase         VARCHAR(16) NOT NULL,
    PRIMARY KEY (schedule_name, at_time)
);

-- Exceptions, not rules: the weekday set says when the market normally trades, this says when it
-- does not despite that.
CREATE TABLE market_holiday (
    schedule_name VARCHAR(64)  NOT NULL REFERENCES session_schedule (name) ON DELETE CASCADE,
    holiday_date  DATE         NOT NULL,
    description   VARCHAR(128),
    PRIMARY KEY (schedule_name, holiday_date)
);

ALTER TABLE shard
    ADD COLUMN schedule_name VARCHAR(64) REFERENCES session_schedule (name);

-- What the scheduler did and why, including what it deliberately did not do. A scheduler that
-- silently skips is indistinguishable from one that is broken.
CREATE TABLE schedule_run (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    shard_id     INTEGER      NOT NULL,
    action       VARCHAR(32)  NOT NULL,
    phase        VARCHAR(16),
    trading_date INTEGER,
    sent         BOOLEAN      NOT NULL,
    confirmed    BOOLEAN      NOT NULL,
    detail       VARCHAR(512)
);

CREATE INDEX schedule_run_at_idx ON schedule_run (at DESC);
