-- Authentication and the audit of who asked.
--
-- The control plane can seed a SecurityDefinition, move a shard's session, purge, reopen a halted
-- security, and run a schedule that opens a market unattended. Until now it did all of that for
-- anyone who could reach the port, and recorded nothing about who. Operator commands are
-- unacknowledged by design (Design.md §7) -- the engine applies or rejects them in silence -- so
-- the control plane's own record of what it sent, and on whose behalf, is the only account of a
-- market-moving action that exists anywhere.

-- One role for now: an authenticated operator has full access. The column exists so that adding a
-- read-only role later is a data change rather than a schema migration; nothing reads a value
-- other than ADMIN yet.
CREATE TABLE control_user (
    username      VARCHAR(64)  PRIMARY KEY CHECK (length(trim(username)) > 0),
    -- BCrypt, always. The column is sized for the {id}-prefixed format Spring Security's
    -- DelegatingPasswordEncoder writes, so an encoder change is not a migration.
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(32)  NOT NULL DEFAULT 'ADMIN' CHECK (role IN ('ADMIN')),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Every market-moving command, with the operator who asked for it and what the control plane could
-- honestly claim about it afterwards.
--
-- `sent` is not `applied`. Nothing acknowledges an operator command, so a row saying sent = true
-- claims only that bytes left for the gateway. Recording the distinction here rather than
-- flattening it to "success" is the same honesty the REST layer already practises by answering
-- 202 rather than 200.
CREATE TABLE operator_audit (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Not a foreign key to control_user: the audit must outlive the account. Deleting an operator
    -- must not delete, or silently anonymise, what they did.
    username   VARCHAR(64)  NOT NULL,
    action     VARCHAR(32)  NOT NULL,
    target     VARCHAR(64),
    detail     VARCHAR(512),
    sent       BOOLEAN      NOT NULL,
    remote_addr VARCHAR(64)
);

CREATE INDEX operator_audit_at_idx ON operator_audit (at DESC);
